Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,22 +1,36 @@
 name: "Build kernels"
 
 env:
-  CONFIGURATION: "repos.json"
   OUT_DIR: "out"
 
 on:
   workflow_dispatch:
+    inputs:
+      config_file:
+        description: "Path to config JSON file"
+        required: true
+        default: "repos.json"
 
 jobs:
   Set-repos:
-    name: "🐂 Parse repos.json"
+    name: "🐂 Parse configuration file"
     runs-on: ubuntu-latest
+    env:
+      CONFIGURATION: ${{ github.event.inputs.config_file }}
     outputs:
       repos: ${{ steps.generate-matrix.outputs.repos }}
     steps:
       - name: "😄 Checkout"
         uses: actions/checkout@v4
 
+
+      - name: "🔍 Check configuration file"
+        run: |
+          if [ ! -f "${{ env.CONFIGURATION }}" ]; then
+            echo "❌ Configuration file ${{ env.CONFIGURATION }} not found!"
+            exit 1
+          fi
+          
       - name: "😆 Generate Matrix"
         id: generate-matrix
         run: |
@@ -29,6 +43,8 @@ jobs:
     runs-on: ubuntu-latest
     needs:
       - Set-repos
+    env:
+      CONFIGURATION: ${{ github.event.inputs.config_file }}
     strategy:
       max-parallel: 2
       fail-fast: false
@@ -52,8 +68,6 @@ jobs:
       - name: "⭐ Install prerequisites"
         run: |
           sudo apt update
-          # sudo add-apt-repository universe
-          # sudo apt -y install python2
           sudo apt install -y build-essential bc curl git zip ftp gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev lftp zstd wget libfl-dev python3 libarchive-tools
 
       - name: "🌟 Clone kernel source => (${{ env.kernelRepo }})"
@@ -163,7 +177,6 @@ jobs:
           name: Image(${{ env.kernelDevice }}-${{ env.kernelName }}-${{ env.kernelBranch }})
           path: ./${{ env.kernelDir }}/${{ env.OUT_DIR }}/arch/${{ env.ARCH }}/boot/Image
           if-no-files-found: ignore
-          retention-days: 7
 
       - name: "💙 Upload Image.gz"
         uses: actions/upload-artifact@v4
@@ -171,7 +184,6 @@ jobs:
           name: Image.gz(${{ env.kernelDevice }}-${{ env.kernelName }}-${{ env.kernelBranch }})
           path: ./${{ env.kernelDir }}/${{ env.OUT_DIR }}/arch/${{ env.ARCH }}/boot/Image.gz*
           if-no-files-found: ignore
-          retention-days: 7
 
       - name: "💜 Upload dtb"
         uses: actions/upload-artifact@v4
@@ -180,7 +192,6 @@ jobs:
           path: ./${{ env.kernelDir }}/${{ env.OUT_DIR }}/arch/${{ env.ARCH }}/boot/dtb*
                 ./${{ env.kernelDir }}/${{ env.OUT_DIR }}/arch/${{ env.ARCH }}/boot/dts/**/*.dtb
           if-no-files-found: ignore
-          retention-days: 7
 
       - name: "❤️ Upload dtbo.img"
         uses: actions/upload-artifact@v4
@@ -188,4 +199,3 @@ jobs:
           name: dtbo.img(${{ env.kernelDevice }}-${{ env.kernelName }}-${{ env.kernelBranch }})
           path: ./${{ env.kernelDir }}/${{ env.OUT_DIR }}/arch/${{ env.ARCH }}/boot/dtbo.img
           if-no-files-found: ignore
-          retention-days: 7
